from selenium import webdriver
driver = webdriver.Chrome()
driver.maximize_window()
driver.implicitly_wait(7)
driver.get('https://practice.automationtesting.in/')
driver.execute_script("window.scrollBy(0,600);")
book = driver.find_element_by_xpath('//img[contains(@title,"Selenium Ruby")]')
book.click()
review_tab = driver.find_element_by_css_selector('.reviews_tab')
review_tab.click()
five = driver.find_element_by_css_selector('.star-5')
five.click()
comment = driver.find_element_by_id('comment')
comment.send_keys('Nice book!')
name = driver.find_element_by_id('author')
name.send_keys('Karina')
email = driver.find_element_by_id('email')
email.send_keys('karina.grisha@yandex.ru')
submit = driver.find_element_by_id('submit')
submit.click()
driver.quit ()
